# Generated by GenAI
FROM node:14

# Set environment variables (hardcoded credentials)
ENV DB_USER=admin
ENV DB_PASS=SuperSecretPassword

# Copy application code
COPY . /app

# Install dependencies
RUN cd /app && npm install

# Expose application port
EXPOSE 8080

# Start the application
CMD ["node", "/app/server.js"]
