name: Snyk Container Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    permissions:
        security-events: write
    runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build the Docker image for the legacy application
      - name: Build Docker image
        run: |
          docker build -t patchcorp/legacy-app:latest .

  scan_and_upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 3: Run Snyk Container scan on the built image
      - name: Snyk Container Scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: patchcorp/legacy-app:latest
          args: --sarif-file-output=snyk.sarif

      - name: Replace security-severity undefined for license-related findings 
        run: |
          sed -i 's/"security-severity": "undefined"/"security-severity": "0"/g' snyk.sarif
          sed -i 's/"security-severity": "null"/"security-severity": "0"/g' snyk.sarif

      # Step 4: Upload result to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  notify_on_slack:
    runs-on: ubuntu-latest
    needs: scan_and_upload
    steps:
      # Step 6: Send a Slack notification for the completed process
      - name: Notify on Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Legacy application container build and container security scan completed successfully. Image: patchcorp/legacy-app:latest."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
